### ISSUE TITLE
Depending on the make command it can show `Nothing to be done` for all even when nothing is compiled

### ISSUE THREAD

**Issue by xexyl** [lcn2/dbg#29]
# Describe the bug

Depending on the targets specified in the same command line the `all` target can end up saying `nothing to be done` in the usual `make(1)` rule without the silencing of the rule if everything is compiled.

What's more if anything needs to be compiled it will compile it rather than say 'Nothing to be done'.

In the case of this command the output does not do this. Even more the same happens (in the same command line) for `clean` and `clobber`.

Nonetheless when running:

```sh
make clobber all clobber all clean
```

the output is the following, after compiling things after the first `clobber`:

```
make: Nothing to be done for 'clobber'.
make: Nothing to be done for 'all'.
make: Nothing to be done for 'clean'.
```

# What do I expect?

I expect, naturally, for the clobber to work and then everything to be compiled and then the `clean` rule should be run as well.

# Platform

macOS .. same version and compiler as you. As for `make(1)` version:

```sh
$ make --version
GNU Make 4.4.1
Built for aarch64-apple-darwin23.0.0
```

But...

```sh
$ /usr/bin/make -v
GNU Make 3.81
```

does the same thing. Does that mean it's the Makefile or not? I have no clue.

# Is this a bug or just a strange and insignificant (or almost insignificant) thing?

I don't know that I could call it a bug. It seems maybe not even a problem with the Makefile (well besides the fact that more than one version of `make(1)` does it I guess) but perhaps it is a problem with running a series of certain make rules on the same command?

# Anything else?

Yes. I'm probably the last one (unless someone wants to play a dirty trick on me :) ) to open an issue without a template existing though I kind of made look like a form .. kind of.

Also this same thing happens or the jparse repo, the dyn_array repo and the mkiocccentry repo (which might be the better place for this but that one already has a lot of issues and this one has no open issues ... and besides that it's also probably not worth worrying about - I guess it's a cosmetic / visual issue at best but I'll leave that to you to decide).

## Other things 

If I run `make all` after this 'failure' it runs fine: everything is compiled.

Also this is not related to the recent commits.

**Comment by lcn2** [comment]
This INABIAF 🤓 of `make(1)`.

If you do:

```sh
make all
```

and then do:

```sh
make all all all
```

You will get 2 "_make: Nothing to be done for `all'._".

Redundant invocations of rules in most `make(1)` command do this.  So:

```sh
make clobber all test install clobber
```

Assuming nothing aborts, will end up with "make: Nothing to be done for `clobber'." because of the 2nd invocation of the "_clobber_" rule.

**Comment by xexyl** [comment]
> This INABIAF 🤓 of `make(1)`.
> 
> 
> 
> If you do:
> 
> 
> 
> ```sh
> 
> make all
> 
> ```
> 
> 
> 
> and then do:
> 
> 
> 
> ```sh
> 
> make all all all
> 
> ```
> 
> 
> 
> You will get 2 "_make: Nothing to be done for `all'._".
> 
> 
> 
> Redundant invocations of rules in most `make(1)` command do this.  So:
> 
> 
> 
> ```sh
> 
> make clobber all test install clobber
> 
> ```
> 
> 
> 
> Assuming nothing aborts, will end up with "make: Nothing to be done for `clobber'." because of the 2nd invocation of the "_clobber_" rule.
> 
> 

I guessed it was something like that BUT the details are very interesting!

It's funny to think about how I brought this up when I also discovered it being the problem you were experiencing. Or something similar. 

Anyway as I think I said I didn't think this was a bug. 

Thanks!
